stages:
  - build
  - deploy

# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - INTERKIT_IMAGE_TAG=latest docker-compose build
    - INTERKIT_IMAGE_TAG=latest docker-compose push
    - INTERKIT_IMAGE_TAG=$CI_COMMIT_SHORT_SHA docker-compose build
    - INTERKIT_IMAGE_TAG=$CI_COMMIT_SHORT_SHA docker-compose push
  only:
    - main

#docker-build:
#  # Official docker image.
#  image: docker:latest
#  stage: build
#  services:
#    - docker:dind
#  before_script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
#    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#  except:
#    - main

.deploy: &deploy
  stage: deploy
  image: ubuntu
  when: manual
  only:
    - main
  except:
    - merge_requests
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo INTERKIT_IMAGE_TAG=$CI_COMMIT_SHORT_SHA > .env
    - echo $INTERKIT_ENV_FILE >> .env
    - scp docker-compose.yml $SSH_USER@$SSH_HOST:~/$CI_PROJECT_NAME/docker-compose.yml
    - scp .env $SSH_USER@$SSH_HOST:~/$CI_PROJECT_NAME/.env
    - echo "cd ~/$CI_PROJECT_NAME && ls -la && docker-compose pull && docker-compose up -d --remove-orphans" | ssh $SSH_USER@$SSH_HOST 

deploy-master-demo:
  <<: *deploy
  environment:
    name: demo
    url: https://demo.interkit.app
  stage: deploy


