stages:
  - build_images
  - publish
  - test
  - deploy_demo

variables:
  DOCKER_IMAGE_TAG: 20
  INTERKIT_BASE_TAG: '${CI_COMMIT_BRANCH}-latest'
  INTERKIT_IMAGE_TAG: '${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}'

.build: &build
  image: docker:$DOCKER_IMAGE_TAG
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

docker-build-server:
  image: docker:$DOCKER_IMAGE_TAG
  stage: build_images
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    #- docker pull interkit/server-base:$INTERKIT_BASE_TAG || true
    #- docker pull interkit/server:$INTERKIT_BASE_TAG || true
    - docker build . --build-arg INTERKIT_BASE_TAG=$INTERKIT_BASE_TAG --target meteor-base --cache-from interkit/server-base:$INTERKIT_BASE_TAG -t interkit/server-base:$INTERKIT_BASE_TAG -f Dockerfile.meteor-server --build-arg BUILDKIT_INLINE_CACHE=1
    - docker build . --build-arg INTERKIT_BASE_TAG=$INTERKIT_BASE_TAG --cache-from interkit/server-base:$INTERKIT_BASE_TAG --cache-from interkit/server:$INTERKIT_BASE_TAG -t interkit/server:$INTERKIT_BASE_TAG -t interkit/server:$INTERKIT_IMAGE_TAG -f Dockerfile.meteor-server --build-arg BUILDKIT_INLINE_CACHE=1
    - docker push interkit/server-base:$INTERKIT_BASE_TAG
    - docker push interkit/server:$INTERKIT_BASE_TAG
    - docker push interkit/server:$INTERKIT_IMAGE_TAG
    - echo DONE

docker-build-bundler:
  # Official docker image.
  image: docker:$DOCKER_IMAGE_TAG
  stage: build_images
  services:
    - docker:dind
  #needs:
  #  - docker-build-base
  before_script:
    - apk add --no-cache docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    #- docker pull interkit/bundler:$INTERKIT_BASE_TAG || true
    - docker build . --build-arg INTERKIT_BASE_TAG=$INTERKIT_BASE_TAG --cache-from interkit/bundler:$INTERKIT_BASE_TAG -t interkit/bundler:$INTERKIT_BASE_TAG -t interkit/bundler:$INTERKIT_IMAGE_TAG -f Dockerfile.app-bundler --build-arg BUILDKIT_INLINE_CACHE=1
    - docker push interkit/bundler:$INTERKIT_BASE_TAG
    - docker push interkit/bundler:$INTERKIT_IMAGE_TAG
    - echo DONE

docker-build-admin:
  # Official docker image.
  image: docker:$DOCKER_IMAGE_TAG
  stage: build_images
  services:
    - docker:dind
  #needs:
  #  - docker-build-base
  before_script:
    - apk add --no-cache docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    #- docker pull interkit/admin:$INTERKIT_BASE_TAG || true
    - docker build . --build-arg INTERKIT_BASE_TAG=$INTERKIT_BASE_TAG --cache-from interkit/admin:$INTERKIT_BASE_TAG -t interkit/admin:$INTERKIT_BASE_TAG -t interkit/admin:$INTERKIT_IMAGE_TAG -f Dockerfile.svelte-admin --build-arg BUILDKIT_INLINE_CACHE=1
    - docker push interkit/admin:$INTERKIT_BASE_TAG
    - docker push interkit/admin:$INTERKIT_IMAGE_TAG
    - echo DONE

docker-build-docs:
  # Official docker image.
  image: docker:$DOCKER_IMAGE_TAG
  stage: build_images
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    #- docker pull interkit/docs:latest || true
    - docker build . -t interkit/docs:latest -f Dockerfile.docs --cache-from interkit/docs:latest --build-arg BUILDKIT_INLINE_CACHE=1
    - docker push interkit/docs:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

deploy-docs:
  # Official docker image.
  image: docker:$DOCKER_IMAGE_TAG
  stage: publish
  needs:
    - docker-build-docs
  before_script:
    - apk add --no-cache curl
  script:
    - curl -X POST http://interkit.intergestalt.cloud:9000/api/webhooks/20f38b1a-a6cf-4d73-9477-bca4e2f24df7
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.deploy: &deploy
  stage: deploy
  image: ubuntu
  needs:
    - docker-build-server
    - docker-build-bundler
    - docker-build-admin
  #only:
  #  - main
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo INTERKIT_IMAGE_TAG=$INTERKIT_IMAGE_TAG > .env
    - echo $INTERKIT_ENV_FILE | tr ' ' '\n' >> .env
    - apt-get install rsync -y
    - rsync -e ssh -v -a {docker-compose.yml,.env} $SSH_USER@$SSH_HOST:~/$CI_COMMIT_BRANCH/
    - echo "cd ~/$CI_COMMIT_BRANCH && ls -la && docker-compose pull && docker-compose up -d --remove-orphans" | ssh $SSH_USER@$SSH_HOST 

deploy-demo:
  <<: *deploy
  rules:
    - if: $INTERKIT_ENV_FILE && '$CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
  environment:
    name: $CI_COMMIT_BRANCH
    url: 'https://${CI_COMMIT_BRANCH}.demo.interkit.app'
  stage: deploy_demo
  #allow_failure: true

publish-package:
  stage: publish
  script:
      - cd packages && tar -a -cf ../interkit.tar.gz interkit && cd -
  artifacts:
    expire_in: 5 yrs
    paths:
      - interkit.tar.gz

test-server:
  image: geoffreybooth/meteor-base:2.5.6
  stage: test
  script:
    - cd meteor-server
    - meteor npm install
    - meteor npm test
