#cloud-config
# ^^^ no space between # and cloud-config --> #cloud-config !
package_update: true
package_upgrade: true
timezone: "Europe/Berlin"
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
runcmd:
  # install docker and docker compose
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  # download interkit docker compose definitions
  - wget https://gitlab.interkit.app/interkit/interkit-experiments/-/raw/v04/docker-compose.env.live.example
  - wget https://gitlab.interkit.app/interkit/interkit-experiments/-/raw/v04/docker-compose.yml
  - wget https://gitlab.interkit.app/interkit/interkit-experiments/-/raw/v04/docker-compose-proxy-live.yml
  # download scripts
  - wget https://gitlab.interkit.app/interkit/interkit-experiments/-/raw/v04/env-configure.sh
  - wget https://gitlab.interkit.app/interkit/interkit-experiments/-/raw/v04/env-randomize.sh
  # generate config
  - cp docker-compose.env.live.example .env
  # ... randomize passwords
  - ./env-randomize.sh
  # ... set domain and password here!
  - ./env-configure.sh -d interkit.app -p password
  # docker compose setup
  - docker network create frontproxy
  - docker compose -f docker-compose.yml -f docker-compose-proxy-live.yml up -d
