FROM node:16-alpine@sha256:a1f9d027912b58a7c75be7716c97cfbc6d3099f3a97ed84aa490be9dee20e787

ARG BUILD_SOURCE_PATH=./svelte-admin

WORKDIR /app

# copy shared files and install dependencies
COPY /packages /packages
RUN cd /packages/interkit && npm ci
RUN cd /packages/interkit-blockly && npm ci

# copy app files and install dependencies
COPY ${BUILD_SOURCE_PATH} ./
RUN npm ci && npm cache clean --force

# build
ENV NODE_OPTIONS="--max-old-space-size=2560"
RUN npm run build

# clean
RUN npm prune --production && rm -rf /packages

CMD ["npm", "start"]
