FROM node:15-alpine

ARG BUILD_SOURCE_PATH

WORKDIR /app

# copy shared files and install dependencies
COPY /packages /packages
RUN cd /packages/interkit && npm ci
RUN cd /packages/interkit-dev && npm ci

# copy app files and install dependencies
COPY ${BUILD_SOURCE_PATH} ./
RUN npm ci

# build
RUN npm run build

CMD ["npm", "start"]
