FROM node:16-alpine

WORKDIR /app

# copy shared files and install dependencies
COPY /packages /packages
RUN cd /packages/interkit && npm ci
#RUN cd /packages/interkit-blockly && npm ci

WORKDIR /app/docs

# copy package.json and install dependencies
COPY sites/docs/package*json ./
RUN npm ci

# copy app files
COPY sites/docs ./

# copy other files that are imported in the docs
COPY meteor-server /meteor-server
COPY app-bundler /app-bundler
COPY repositories/starters /repositories/starters

# build
RUN npm run build

# clean
RUN npm prune --production && rm -rf /packages && rm -rf /meteor-server && rm -rf /app-bundler

EXPOSE 3000
CMD ["node", "build"]
