version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: interkit/server:${INTERKIT_IMAGE_TAG}
    build:
      context: ./
      dockerfile: Dockerfile.meteor-server
      args:
        BUILD_SOURCE_PATH: ./meteor-server
        BUILD_REPOSITORIES_PATH: ./repositories
        BUILD_CONTAINER_REPOSITORIES_PATH: /var/repositories
    ports:
      - '3000:3000'
    volumes:
      - projects:/var/repositories/projects
      - mediafiles:/var/mediafiles
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${INTERKIT_SERVER_URL:-http://localhost:3000}
      MONGO_URL: mongodb://mongo:27017/meteor
      REPOSITORIES_PATH: /var/repositories
      MEDIAFILES_PATH: /var/mediafiles
      PORT: 3000
      BUNDLER_URL: ${INTERKIT_BUNDLER_URL:-http://localhost:4000}
      LETSENCRYPT_HOST: $INTERKIT_SERVER_HOST
      LETSENCRYPT_EMAIL: info@interkit.app
      VIRTUAL_HOST: $INTERKIT_SERVER_HOST
      VIRTUAL_PORT: 3000
      ADMIN_PASSWORD: $INTERKIT_ADMIN_PASSWORD

  mongo:
    image: mongo:4.2
    command:
      - --storageEngine=wiredTiger
    volumes:
      - db-data:/data/db

  admin:
    image: interkit/admin:${INTERKIT_IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./Dockerfile.svelte-admin
      args:
        BUILD_SOURCE_PATH: ./svelte-admin
    ports:
      - '5000:5000'
    environment:
      INTERKIT_SERVER_WEBSOCKETS_URL: ${INTERKIT_SERVER_WEBSOCKETS_URL:-ws://localhost:3000/websocket}
      INTERKIT_SERVER_URL: ${INTERKIT_SERVER_URL:-http://localhost:3000}
      LETSENCRYPT_HOST: $INTERKIT_ADMIN_HOST
      LETSENCRYPT_EMAIL: info@interkit.app
      VIRTUAL_HOST: $INTERKIT_ADMIN_HOST
      VIRTUAL_PORT: 5000

  bundler:
    image: interkit/bundler:${INTERKIT_IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./Dockerfile.app-bundler
      args:
        BUILD_SOURCE_PATH: ./app-bundler
        BUILD_REPOSITORIES_PATH: ./repositories
    ports:
      - '4000:4000'
    volumes:
    - projects:/var/repositories/projects
    environment:
      PORT: 4000
      LETSENCRYPT_HOST: $INTERKIT_BUNDLER_HOST
      LETSENCRYPT_EMAIL: info@interkit.app
      VIRTUAL_HOST: $INTERKIT_BUNDLER_HOST
      VIRTUAL_PORT: 4000
    

volumes:
  db-data:
  #repositories:
  #  driver_opts:
  #    type: none
  #    device: ./repositories
  #    o: bind
  projects:
  mediafiles:
  certs:
  html:
  vhost:
  conf:
  dhparam:
  acme:
