FROM interkit/interkit-packages:latest AS interkit-packages
FROM node:15

ARG BUILD_SOURCE_PATH=./app-bundler
ARG BUILD_REPOSITORIES_PATH=./repositories

WORKDIR /app

# copy shared files
COPY --from=interkit-packages /packages /packages

# install dependencies
COPY ${BUILD_SOURCE_PATH}/package*json ./
#RUN npm i @node-rs/bcrypt-linux-musl
#RUN apt-get update && apt-get install musl
RUN npm ci
RUN npx node-prune --yes

# copy app files
COPY ${BUILD_SOURCE_PATH} ./

# copy shared files AGAIN for starters
COPY --from=interkit-packages /packages /var/packages

# set repositories path in container
ENV REPOSITORIES_PATH=/var/repositories
# Copy repositories folder
COPY ${BUILD_REPOSITORIES_PATH} ${REPOSITORIES_PATH}
# set REPOSITORIES_PATH at runtime
RUN echo "REPOSITORIES_PATH=${REPOSITORIES_PATH}" > .env

# npm install starter
# RUN cd ${REPOSITORIES_PATH}/starters/cs1 && npm ci


CMD ["npm", "start"]
