version: '3'

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
        #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=info@interkit.app"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  server:
    image: interkit/server:${INTERKIT_IMAGE_TAG}
    build:
      context: ./
      dockerfile: Dockerfile.meteor-server
      args:
        BUILD_SOURCE_PATH: ./meteor-server
        BUILD_REPOSITORIES_PATH: ./repositories
        BUILD_CONTAINER_REPOSITORIES_PATH: /var/repositories
    ports:
      - '3000:3000'
    volumes:
      - projects:/var/repositories/projects
      - mediafiles:/var/mediafiles
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${INTERKIT_SERVER_URL:-http://localhost:3000}
      MONGO_URL: mongodb://mongo:27017/meteor
      REPOSITORIES_PATH: /var/repositories
      MEDIAFILES_PATH: /var/mediafiles
      PORT: 3000
      BUNDLER_URL: ${INTERKIT_BUNDLER_URL:-http://localhost:4000}
      ADMIN_PASSWORD: $INTERKIT_ADMIN_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`${INTERKIT_SERVER_HOST}`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=letsencrypt"

  mongo:
    image: mongo:4.2
    command:
      - --storageEngine=wiredTiger
    volumes:
      - db-data:/data/db

  admin:
    image: interkit/admin:${INTERKIT_IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./Dockerfile.svelte-admin
      args:
        BUILD_SOURCE_PATH: ./svelte-admin
    ports:
      - '5000:5000'
    environment:
      INTERKIT_SERVER_WEBSOCKETS_URL: ${INTERKIT_SERVER_WEBSOCKETS_URL:-ws://localhost:3000/websocket}
      INTERKIT_SERVER_URL: ${INTERKIT_SERVER_URL:-http://localhost:3000}
      INTERKIT_IMAGE_TAG: $INTERKIT_IMAGE_TAG
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`${INTERKIT_ADMIN_HOST}`)"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=letsencrypt"

  bundler:
    image: interkit/bundler:${INTERKIT_IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./Dockerfile.app-bundler
      cache_from: interkit/bundler:latest
      args:
        BUILD_SOURCE_PATH: ./app-bundler
        BUILD_REPOSITORIES_PATH: ./repositories
    ports:
      - '4000:4000'
    volumes:
    - projects:/var/repositories/projects
    environment:
      PORT: 4000
      ADMIN_PASSWORD: ${INTERKIT_ADMIN_PASSWORD}
      INTERKIT_BUNDLER_URL: ${INTERKIT_BUNDLER_URL:-http://localhost:4000}
      INTERKIT_SERVER_WEBSOCKETS_URL: ${INTERKIT_SERVER_WEBSOCKETS_URL:-ws://localhost:3000/websocket}
      INTERKIT_SERVER_URL: ${INTERKIT_SERVER_URL:-http://localhost:3000}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bundler.rule=Host(`${INTERKIT_BUNDLER_HOST}`)"
      - "traefik.http.routers.bundler.entrypoints=websecure"
      - "traefik.http.routers.bundler.tls.certresolver=letsencrypt"

volumes:
  db-data:
  #repositories:
  #  driver_opts:
  #    type: none
  #    device: ./repositories
  #    o: bind
  projects:
  mediafiles:
  letsencrypt:
