FROM node:16-alpine

ARG BUILD_SOURCE_PATH=./svelte-admin

WORKDIR /app

# copy shared files and install dependencies
COPY /packages /packages
RUN cd /packages/interkit && npm ci
RUN cd /packages/interkit-blockly && npm ci

# copy app files and install dependencies
COPY ${BUILD_SOURCE_PATH} ./
RUN npm ci && npm cache clean --force

# build
RUN npm run build

# clean
RUN npm prune --production && rm -rf /packages

CMD ["npm", "start"]
