FROM node:16

ARG BUILD_REPOSITORIES_PATH=./repositories

WORKDIR /app

# copy shared files and install dependencies
COPY /packages /packages
RUN cd /packages/interkit && npm ci

# install dependencies
COPY ./app-bundler/package*json ./
#RUN npm i @node-rs/bcrypt-linux-musl
#RUN apt-get update && apt-get install musl
RUN npm ci
#RUN npx node-prune --yes

# copy app files
COPY ./app-bundler ./

# copy shared files AGAIN for starters
RUN cp -r /packages /var/packages

# set repositories path in container
ENV REPOSITORIES_PATH=/var/repositories
# Copy repositories folder
COPY ${BUILD_REPOSITORIES_PATH} ${REPOSITORIES_PATH}
# set REPOSITORIES_PATH at runtime
RUN echo "REPOSITORIES_PATH=${REPOSITORIES_PATH}" > .env

# npm install starter
# RUN cd ${REPOSITORIES_PATH}/starters/starter && npm ci

# Rest of your Dockerfile instructions...


CMD ["npm", "start"]
