import { createRoleIdempotent } from '../imports/userRoles.js';

/* roles */

createRoleIdempotent("admin")
createRoleIdempotent("author")
createRoleIdempotent("bundler")
createRoleIdempotent("projectserver")
createRoleIdempotent("projectuser")


/* capabilities */

/*
Roles.createRole("projects.insert")
Roles.createRole("projects.remove")
Roles.createRole("projects.view"  )
Roles.createRole("projects.edit"  )
Roles.createRole("projects.list"  )
Roles.createRole("users.insert"   )
Roles.createRole("users.remove"   )
Roles.createRole("users.view"     )
Roles.createRole("users.edit"     )
Roles.createRole("users.list"     )
Roles.createRole("messages.insert")
Roles.createRole("messages.remove")
Roles.createRole("messages.view"  )
Roles.createRole("messages.edit"  )
Roles.createRole("messages.list"  )
Roles.createRole("channels.insert")
Roles.createRole("channels.remove")
Roles.createRole("channels.view"  )
Roles.createRole("channels.edit"  )
Roles.createRole("channels.list"  )
Roles.createRole("sheets.insert"  )
Roles.createRole("sheets.remove"  )
Roles.createRole("sheets.view"    )
Roles.createRole("sheets.edit"    )
Roles.createRole("sheets.list"    )
Roles.createRole("rows.insert"    )
Roles.createRole("rows.remove"    )
Roles.createRole("rows.view"      )
Roles.createRole("rows.edit"      )
Roles.createRole("rows.list"      )
Roles.createRole("media.insert"   )
Roles.createRole("media.remove"   )
Roles.createRole("media.view"     )
Roles.createRole("media.edit"     )
Roles.createRole("media.list"     )
*/

/* assign admin */

/*
Roles.addRolesToParent("projects.insert", "admin")
Roles.addRolesToParent("projects.remove", "admin")
Roles.addRolesToParent("projects.view"  , "admin")
Roles.addRolesToParent("projects.edit"  , "admin")
Roles.addRolesToParent("projects.list"  , "admin")
Roles.addRolesToParent("users.insert"   , "admin")
Roles.addRolesToParent("users.remove"   , "admin")
Roles.addRolesToParent("users.view"     , "admin")
Roles.addRolesToParent("users.edit"     , "admin")
Roles.addRolesToParent("users.list"     , "admin")
Roles.addRolesToParent("messages.insert", "admin")
Roles.addRolesToParent("messages.remove", "admin")
Roles.addRolesToParent("messages.view"  , "admin")
Roles.addRolesToParent("messages.edit"  , "admin")
Roles.addRolesToParent("messages.list"  , "admin")
Roles.addRolesToParent("channels.insert", "admin")
Roles.addRolesToParent("channels.remove", "admin")
Roles.addRolesToParent("channels.view"  , "admin")
Roles.addRolesToParent("channels.edit"  , "admin")
Roles.addRolesToParent("channels.list"  , "admin")
Roles.addRolesToParent("sheets.insert"  , "admin")
Roles.addRolesToParent("sheets.remove"  , "admin")
Roles.addRolesToParent("sheets.view"    , "admin")
Roles.addRolesToParent("sheets.edit"    , "admin")
Roles.addRolesToParent("sheets.list"    , "admin")
Roles.addRolesToParent("rows.insert"    , "admin")
Roles.addRolesToParent("rows.remove"    , "admin")
Roles.addRolesToParent("rows.view"      , "admin")
Roles.addRolesToParent("rows.edit"      , "admin")
Roles.addRolesToParent("rows.list"      , "admin")
Roles.addRolesToParent("media.insert"   , "admin")
Roles.addRolesToParent("media.remove"   , "admin")
Roles.addRolesToParent("media.view"     , "admin")
Roles.addRolesToParent("media.edit"     , "admin")
Roles.addRolesToParent("media.list"     , "admin")
*/

/* assign author */

/*
Roles.addRolesToParent("projects.insert", "author")
Roles.addRolesToParent("projects.remove", "author")
Roles.addRolesToParent("projects.view"  , "author")
Roles.addRolesToParent("projects.edit"  , "author")
Roles.addRolesToParent("projects.list"  , "author")
Roles.addRolesToParent("users.insert"   , "author")
Roles.addRolesToParent("users.remove"   , "author")
Roles.addRolesToParent("users.view"     , "author")
Roles.addRolesToParent("users.edit"     , "author")
Roles.addRolesToParent("users.list"     , "author")
Roles.addRolesToParent("messages.insert", "author")
Roles.addRolesToParent("messages.remove", "author")
Roles.addRolesToParent("messages.view"  , "author")
Roles.addRolesToParent("messages.edit"  , "author")
Roles.addRolesToParent("messages.list"  , "author")
Roles.addRolesToParent("channels.insert", "author")
Roles.addRolesToParent("channels.remove", "author")
Roles.addRolesToParent("channels.view"  , "author")
Roles.addRolesToParent("channels.edit"  , "author")
Roles.addRolesToParent("channels.list"  , "author")
Roles.addRolesToParent("sheets.insert"  , "author")
Roles.addRolesToParent("sheets.remove"  , "author")
Roles.addRolesToParent("sheets.view"    , "author")
Roles.addRolesToParent("sheets.edit"    , "author")
Roles.addRolesToParent("sheets.list"    , "author")
Roles.addRolesToParent("rows.insert"    , "author")
Roles.addRolesToParent("rows.remove"    , "author")
Roles.addRolesToParent("rows.view"      , "author")
Roles.addRolesToParent("rows.edit"      , "author")
Roles.addRolesToParent("rows.list"      , "author")
Roles.addRolesToParent("media.insert"   , "author")
Roles.addRolesToParent("media.remove"   , "author")
Roles.addRolesToParent("media.view"     , "author")
Roles.addRolesToParent("media.edit"     , "author")
Roles.addRolesToParent("media.list"     , "author")
*/

/* assign bundler */

/*
Roles.addRolesToParent("projects.insert", "bundler")
Roles.addRolesToParent("projects.remove", "bundler")
Roles.addRolesToParent("projects.view"  , "bundler")
Roles.addRolesToParent("projects.edit"  , "bundler")
Roles.addRolesToParent("projects.list"  , "bundler")
Roles.addRolesToParent("users.insert"   , "bundler")
Roles.addRolesToParent("users.remove"   , "bundler")
Roles.addRolesToParent("users.view"     , "bundler")
Roles.addRolesToParent("users.edit"     , "bundler")
Roles.addRolesToParent("users.list"     , "bundler")
Roles.addRolesToParent("messages.insert", "bundler")
Roles.addRolesToParent("messages.remove", "bundler")
Roles.addRolesToParent("messages.view"  , "bundler")
Roles.addRolesToParent("messages.edit"  , "bundler")
Roles.addRolesToParent("messages.list"  , "bundler")
Roles.addRolesToParent("channels.insert", "bundler")
Roles.addRolesToParent("channels.remove", "bundler")
Roles.addRolesToParent("channels.view"  , "bundler")
Roles.addRolesToParent("channels.edit"  , "bundler")
Roles.addRolesToParent("channels.list"  , "bundler")
Roles.addRolesToParent("sheets.insert"  , "bundler")
Roles.addRolesToParent("sheets.remove"  , "bundler")
Roles.addRolesToParent("sheets.view"    , "bundler")
Roles.addRolesToParent("sheets.edit"    , "bundler")
Roles.addRolesToParent("sheets.list"    , "bundler")
Roles.addRolesToParent("rows.insert"    , "bundler")
Roles.addRolesToParent("rows.remove"    , "bundler")
Roles.addRolesToParent("rows.view"      , "bundler")
Roles.addRolesToParent("rows.edit"      , "bundler")
Roles.addRolesToParent("rows.list"      , "bundler")
Roles.addRolesToParent("media.insert"   , "bundler")
Roles.addRolesToParent("media.remove"   , "bundler")
Roles.addRolesToParent("media.view"     , "bundler")
Roles.addRolesToParent("media.edit"     , "bundler")
Roles.addRolesToParent("media.list"     , "bundler")
*/

/* assign projectuser */

/*
//Roles.addRolesToParent("projects.insert", "projectuser")
//Roles.addRolesToParent("projects.remove", "projectuser")
  Roles.addRolesToParent("projects.view"  , "projectuser")
//Roles.addRolesToParent("projects.edit"  , "projectuser")
//Roles.addRolesToParent("projects.list"  , "projectuser")
//Roles.addRolesToParent("users.insert"   , "projectuser")
//Roles.addRolesToParent("users.remove"   , "projectuser")
  Roles.addRolesToParent("users.view"     , "projectuser")
  Roles.addRolesToParent("users.edit"     , "projectuser")
//Roles.addRolesToParent("users.list"     , "projectuser")
  Roles.addRolesToParent("messages.insert", "projectuser")
//Roles.addRolesToParent("messages.remove", "projectuser")
//Roles.addRolesToParent("messages.view"  , "projectuser")
//Roles.addRolesToParent("messages.edit"  , "projectuser")
//Roles.addRolesToParent("messages.list"  , "projectuser")
//Roles.addRolesToParent("channels.insert", "projectuser")
//Roles.addRolesToParent("channels.remove", "projectuser")
  Roles.addRolesToParent("channels.view"  , "projectuser")
//Roles.addRolesToParent("channels.edit"  , "projectuser")
  Roles.addRolesToParent("channels.list"  , "projectuser")
//Roles.addRolesToParent("sheets.insert"  , "projectuser")
//Roles.addRolesToParent("sheets.remove"  , "projectuser")
  Roles.addRolesToParent("sheets.view"    , "projectuser")
//Roles.addRolesToParent("sheets.edit"    , "projectuser")
  Roles.addRolesToParent("sheets.list"    , "projectuser")
  Roles.addRolesToParent("rows.insert"    , "projectuser")
  Roles.addRolesToParent("rows.remove"    , "projectuser")
  Roles.addRolesToParent("rows.view"      , "projectuser")
  Roles.addRolesToParent("rows.edit"      , "projectuser")
  Roles.addRolesToParent("rows.list"      , "projectuser")
  Roles.addRolesToParent("media.insert"   , "projectuser")
  Roles.addRolesToParent("media.remove"   , "projectuser")
  Roles.addRolesToParent("media.view"     , "projectuser")
  Roles.addRolesToParent("media.edit"     , "projectuser")
  Roles.addRolesToParent("media.list"     , "projectuser")
*/